# 文件路径: .github/workflows/metrics.yml
name: GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # 需要在GitHub设置中创建此令牌
          
          # 基本配置
          user: MilesSG
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Shanghai
          
          # 插件配置
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_followup: yes
          plugin_followup_sections: repositories, issues, pulls
