# 文件路径: .github/workflows/update-readme.yml
name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'  # 正确格式：分 时 日 月 星期
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
