name: Update Recent Activity

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Update Recent Activity
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update recent activity"
          section_name: "activity"
          readme_path: "README.md"
