# 文件路径: .github/workflows/update-readme.yml
name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有写入权限
    steps:
      - uses: actions/checkout@v3  # 更新到v3版本
        with:
          fetch-depth: 0  # 获取完整历史以确保活动可见
      
      - name: Update README with latest activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update README with recent activity'
          MAX_LINES: 5  # 显示最近5条活动
